### ISSUE TITLE
OpenSSL3-RSAMB kubernetes-config.yaml CONFIG is always set to "qat-rsa"

### ISSUE THREAD

**Issue by saiprasanna7** [intel/workload-services-framework#30]
### Summary
When running the OpenSSL3-RSAMB workload with various qatsw_* test cases, the Kubernetes configuration consistently points to "qat-rsa" 

### Workload Release Version
v23.2

### Configuration 
-- Setting: PLATFORM=SRF, ARCH=linux/amd64
-- Setting: REGISTRY=docker-registry.services.svc.cluster.local:5000/workload_public/openssl3-rsamb/
-- Setting: RELEASE=:v23.2
-- Setting: TIMEOUT=86400
-- Setting: BENCHMARK=OpenSSL3-RSAMB
-- Setting: BACKEND=kubernetes

### Issue 
During our testing of OpenSSL3-RSAMB with multiple qatsw_* test cases, we observed that the test_openssl3_rsamb_qatsw_* consistently produces RSA KPI results. An interesting observation is that the Kubernetes configuration file (kubernetes-config.yaml) is generated by ctest.sh sets the CONFIG environment variable to "qat-rsa" for all these test cases.

The below kubernetes-config.yaml is from running ctest.sh with test_openssl3_rsamb_qatsw_aes-gcm testcase,
```
#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: openssl3-rsamb-qat-sw:v23.2
        imagePullPolicy: Always
        env:
      containers:
      - name: benchmark
        image: openssl3-rsamb-qat-sw:v23.2
        imagePullPolicy: Always
        env:
        - name: CONFIG
          value: "qat-rsa"
        securityContext:
          privileged: true
      restartPolicy: Never
  backoffLimit: 4
```

### Expected

```
#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#


apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: openssl3-rsamb-qat-sw:v23.2
        imagePullPolicy: Always
        env:
      containers:
      - name: benchmark
        image: openssl3-rsamb-qat-sw:v23.2
        imagePullPolicy: Always
        env:
        - name: CONFIG
          value: "qat-aes-gcm"
        securityContext:
          privileged: true
      restartPolicy: Never
  backoffLimit: 4
```
